# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2205a8a88e90ab53ed014dbd73815d0021f53b79d4cba1b1e29d762305daf73dfa0eb9b0146f54dffb71caa3717b1bee5342b350909e95633db07bf105a53256

test:
  secret_key_base: a0bea9484d511cb7e5a49abc76cd8a216282c51085fa0dfdd1bb4e6cea4900c43f773580de128ac31bd5066c3f8e3c194bab58a91e4547557346de6e5824c5ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
